# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    prettydate.twig_extension:
        class: SocialBundle\Twig\PrettydateExtension
        public: false
        tags:
            - { name: twig.extension }