social_home:
    path:     /
    defaults: { _controller: SocialBundle:Main:home }

social_problem_add:
    path:    /problem-add
    defaults: { _controller: SocialBundle:Main:problemAdd }

social_problem_add_upload:
    path:    /problem-add-upload
    defaults: { _controller: SocialBundle:Main:problemAddUpload }

social_problem_show:
    path:    /problem-page/{problem_titreSlug}
    defaults: { _controller: SocialBundle:Main:problemShow }

social_problem_remove:
    path:    /problem-remove/{problem_titreSlug}
    defaults: { _controller: SocialBundle:Main:problemRemove }

social_problem_solved:
    path:    /problem-solved/{problem_titreSlug}/{comment_id}
    defaults: { _controller: SocialBundle:Main:problemSolved, comment_id: -1 }

social_problem_comment_add:
    path:    /comment-add/{problem_id}/{comFromId}
    defaults: { _controller: SocialBundle:Main:problemCommentAdd, comFromId: -1 }

social_problem_comment_remove:
    path:    /comment-remove/{comment_id}
    defaults: { _controller: SocialBundle:Main:problemCommentRemove }

social_notification_get:
    path:    /notification-get
    defaults: { _controller: SocialBundle:Notification:getNotification }

social_notification_opened:
    path:    /notification-opened/{listeId}/{clear}
    defaults: { _controller: SocialBundle:Notification:openedNotification, listeId: -1, clear: 0 }