social_home:
    path:     /
    defaults: { _controller: SocialBundle:Main:home }

social_problem_add:
    path:    /problem-add
    defaults: { _controller: SocialBundle:Main:problemAdd }

social_problem_add_upload:
    path:    /problem-add-upload
    defaults: { _controller: SocialBundle:Main:problemAddUpload }