social_home:
    path:     /
    defaults: { _controller: SocialBundle:Main:home }

social_problem_add:
    path:    /problem-add
    defaults: { _controller: SocialBundle:Main:problemAdd }

social_problem_add_upload:
    path:    /problem-add-upload
    defaults: { _controller: SocialBundle:Main:problemAddUpload }

social_problem_show:
    path:    /problem-page/{problem_titreSlug}
    defaults: { _controller: SocialBundle:Main:problemShow }

social_problem_comment_add:
    path:    /comment-add/{problem_id}
    defaults: { _controller: SocialBundle:Main:problemCommentAdd }

social_problem_comment_remove:
    path:    /comment-remove/{comment_id}
    defaults: { _controller: SocialBundle:Main:problemCommentRemove }