<?php

namespace SocialBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
	public function findResponses($problem)
	{
		$qb = $this->createQueryBuilder("c");
		
		$qb
			->where("c.problem = :problem")
				->setParameter("problem", $problem)
			->andWhere("c.comFrom IS NOT NULL")
			->orderBy("c.date", "DESC")
		;
		
		return $qb
			->getQuery()
			->getResult()
		;
	}
}
